### ISSUE TITLE
Prevent pull request and issues in read-only repos

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#252]
We don't want issues in subrepos: https://github.com/cucumber/cucumber-expressions-ruby/pulls

* [ ] Add a CONTRIBUTING.md file in each subrepo, informing them to create PRs against cucumber/cucumber
* [x] Disable issues in each subrepo
* [x] Prepend `Read Only` to the GitHub description of each subrepo

**Comment by jaysonesmith** [comment]
Hah! Fancy seeing this after I did just what this ticket is meant to prevent? 😛

**Comment by aslakhellesoy** [comment]
Heh -yes I realised it wasn't obvious, so I want to make it more obvious. Sorry for wasting your time @jaysonesmith - we're not used new contributors becoming active this quickly! :-)

**Comment by jaysonesmith** [comment]
@aslakhellesoy Do you have a list of the RO repos? I could handle the contributing part for you if you'd like?

**Comment by aslakhellesoy** [comment]
I've changed my mind. PRs against subrepos are fine.
