### ISSUE TITLE
Release Cucumber-Ruby 4.0.0 with the gherkin-go parser

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#586]
# Goals
- Release `Rule` and `Example` keywords
- Learn whether bundled executables is a viable strategy - based on feedback on slack and twitter

# Tasks
- [x] Make a new release of `c21e`
- [x] Make a new release of `cucumber-expressions-ruby`
- [x] Make a new release of `cucumber-messages-ruby`
  - [x] Make build work for different combinations of Ruby / google-protobuf
  - [ ] Add docs for installing cucumber* on versions of ruby that require older versions of protobuf
- [ ] Make a new release of `gherkin-ruby`
- [ ] Make a new release of `cucumber-ruby-core`
- [ ] Make a new release of `cucumber-ruby-wire`
- [ ] Use the new version of all of the above in `cucumber-ruby`
- [ ] Upgrade other libraries
- [x] Write a blog post for major release
  - Announce `Rule` keyword and `Example` synonym, explain relationship with Example Mapping
    - Use the train booking example
  - Explain internal changes at a high level (Go executables) and firewall risks. What to do if people have problems -> GitHub issue
  - Explain that people should stick to previous version in case of problems
  - Explain that Rules are coming to JVM/JS later - help needed
  - Mention cukenfest open source day, roadmap etc.
- [ ] Update docs.cucumber.io with information about `Rule` and `Example`
- [ ] Request for feedback message on install
- [ ] Release it
- [ ] Announce it
  - [ ] Slack
  - [ ] Twitter
  - [ ] Mailing list
  - [ ] Newsletter
